version: '3.7'
services:
  redis:
    container_name: redis
    image: 'redis:7'
    command: bash -c "redis-server --appendonly yes --requirepass redis"
    ports:
      - "6379:6379"
    networks:
      - verifier-network
    volumes:
      - dbvol:/data
  ordersDB:
    container_name: ordersDB
    image: mysql:8.0
    networks:
      - verifier-network
    environment:
      - MYSQL_USER=verifier-user
      - MYSQL_PASSWORD=verifier-pass
      - MYSQL_DATABASE=ordersDB
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - dbvol:/var/lib/my_sql
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
    restart: always

  verifier-app:
    build:
      context: .
    container_name: verifier-app
    image: verifier-app
    ports:
      - "8080:8080"
    networks:
      - verifier-network
    links:
      - redis
    depends_on:
      - ordersDB
    environment:
      - MYSQL_HOST=ordersDB
      - MYSQL_USER=verifier-user
      - MYSQL_PASSWORD=verifier-pass
      - MYSQL_DATABASE=ordersDB
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PASS=redis
      - REDIS_PORT=6379
      - REDIS_LOG_KEY=TradesLog

  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: verifier-network
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:8.5.2
    network_mode: verifier-network
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=prometheus
      # Enabled for logging
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

networks:
  verifier-network:
    name: verifier-network

volumes:
  dbvol: