version: '3.7'
services:
  redis:
    container_name: redis
    image: 'redis:7'
    command: bash -c "redis-server --appendonly yes --requirepass redis"
    ports:
      - "6379:6379"
    networks:
      - verifier-network
    volumes:
      - dbvol:/data
  ordersDB:
    container_name: ordersDB
    image: mysql:8.0
    networks:
      - verifier-network
    environment:
      - MYSQL_USER=verifier-user
      - MYSQL_PASSWORD=verifier-pass
      - MYSQL_DATABASE=ordersDB
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - dbvol:/var/lib/my_sql
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
    restart: always

  verifier-app:
    build:
      context: .
    container_name: verifier-app
    image: verifier-app
    ports:
      - "8080:8080"
    networks:
      - verifier-network
    links:
      - redis
    depends_on:
      - ordersDB
    environment:
      - MYSQL_HOST=ordersDB
      - MYSQL_USER=verifier-user
      - MYSQL_PASSWORD=verifier-pass
      - MYSQL_DATABASE=ordersDB
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PASS=redis
      - REDIS_PORT=6379
      - REDIS_LOG_KEY=TradesLog

networks:
  verifier-network:
    name: verifier-network

volumes:
  dbvol: